services:
  api:
    image: host.docker.internal:5000/learningenglish-api:latest
    container_name: backendasp-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=Db_Test_Elearning;Username=postgres;Password=05022004
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: backendasp-db
    environment:
      POSTGRES_DB: Db_Test_Elearning
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 05022004
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
